service: IoT-SES-EmailsRestApi
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
functions:
  mailer:
    handler: createEmail.handler
    events:
      - http:
          path: /api/v0/emails/send
          method: POST

  createSms:
    handler: createSms.handler
    events:
      - httpApi:
          path: /api/v0/sms/send
          method: POST