service: nodemailer
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
functions:
  mailer:
    handler: index.handler
    events:
      - http:
          path: /api/v0/mails/send
          method: POST